// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAxOq8zDecQdBMbGGlunQAtE9HhJyoxHI',
    appId: '1:502388246119:web:da2dadfc8f9f816a3ff6c2',
    messagingSenderId: '502388246119',
    projectId: 'ktf-dev',
    authDomain: 'ktf-dev.firebaseapp.com',
    storageBucket: 'ktf-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS10_TXiMY9YefPoKaSw-g_b9SKl5KkSQ',
    appId: '1:502388246119:android:31a241f6a950fb3e3ff6c2',
    messagingSenderId: '502388246119',
    projectId: 'ktf-dev',
    storageBucket: 'ktf-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0QucHJI2zyxoLnk6fOddjSgJvC-ktGo',
    appId: '1:502388246119:ios:8ce05522441df3793ff6c2',
    messagingSenderId: '502388246119',
    projectId: 'ktf-dev',
    storageBucket: 'ktf-dev.appspot.com',
    iosClientId: '502388246119-jjs5mige3q66l7apsagh7k19mq5u57o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ktf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0QucHJI2zyxoLnk6fOddjSgJvC-ktGo',
    appId: '1:502388246119:ios:8ce05522441df3793ff6c2',
    messagingSenderId: '502388246119',
    projectId: 'ktf-dev',
    storageBucket: 'ktf-dev.appspot.com',
    iosClientId: '502388246119-jjs5mige3q66l7apsagh7k19mq5u57o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ktf',
  );
}
